version: "3"
services:
   registry:
    container_name: registry
    restart: always
    image: registry:2
    ports:
     - "5001:5000"
    volumes:
     - /mnt/data/registry-data:/var/lib/registry
     - ./registry-config/config.yml:/etc/docker/registry/config.yml

   ui:
    container_name: ui
    image: joxit/docker-registry-ui:latest
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=Local Docker Registry
      - REGISTRY_URL=http://localhost:5001
      - SINGLE_REGISTRY=true
    depends_on:
      - registry